# Do Not change this Base url
BASE_URL:  "https://{0}.execute-api.us-west-2.amazonaws.com/dev"
END_POINTS_URL: "https://iwtrjplex7.execute-api.us-west-2.amazonaws.com/dev/endpoints"

TEMP_KEY: 'bb90c867-a02e-4868-bfff-a8ef9c5f68eb2'
SEED_JOB_ID: 'e3b3d908-c916-42ae-964f-ebba727a00ab'
DELETE_JOB_ID: 'd63f774c-2e3b-48fb-a0ce-f4db1effc8cc'
SOURCE_SYSTEM_ID: '86dc65e4-42a0-4ee8-91e8-f201678f53aa'

LOGIN_URL: "https://sso.teradatacloud.io/oauth/token"

client_id: "h4psC1NTevUPYCJ6hTa76htrup4UNIyq"
audience: "https://dev.api.teradatacloud.io/"
grant_type: "http://auth0.com/oauth/grant-type/password-realm"
customer_realm: "AD-DEV"
sysops_realm: "DSS"
agent_realm: "DSS"
scope: "openid profile"

customer_username: "customer.one"
customer_password:
sysops_username: "ed5f350f-5e96-41e7-b24f-27e007578cec"
sysops_password:
agent_username: "f156ba27-5c88-4a03-b033-dcbb7d2bc1ec"
agent_password: