CUSTOMER_SERVICE_URL: "https://oywvlaayha.execute-api.us-west-2.amazonaws.com/dev/customer-profiles/"

INVENTORY_SERVICE_URL: "https://ipn2b7o6dj.execute-api.us-west-2.amazonaws.com/sb186123dev/inventory/items"

SYSTEM_SERVICE_URL: "https://tlgz19gbal.execute-api.us-west-2.amazonaws.com/dev/system"

SYSTEM_API_URL: "https://tlgz19gbal.execute-api.us-west-2.amazonaws.com/dev/"

SEED_JOB_URL: "https://ulqh6w1du6.execute-api.us-west-2.amazonaws.com/dev/seed-jobs/"

AGENT_SERVICE_URL: "https://4k0bte7z20.execute-api.us-west-2.amazonaws.com/dev/agent"

TICKET_SERVICE_URL: "https://wl0qnbvoqf.execute-api.us-west-2.amazonaws.com/vr186027dev/tickets/{ticket_id}"

TEMP_KEY: 'bb90c867-a02e-4868-bfff-a8ef9c5f68eb2'
SEED_JOB_ID: 'ee5ca93d-a60f-4655-9bde-9fad3304cb0f'
DELETE_JOB_ID: '30b93452-71c3-4522-909b-016ea82ee13d'
