# Do Not change this Base url
BASE_URL:  "https://{0}.execute-api.us-west-2.amazonaws.com/dev/"

# eg: 
#     https://oywvlaayha.execute-api.us-west-2.amazonaws.com/dev/
#     Here api_id: oywvlaayha
CUSTOMER_SERVICE_API_ID: "oywvlaayha"
INVENTORY_SERVICE_API_ID: "vrrw4gamg3"
SYSTEM_SERVICE_API_ID: "tlgz19gbal"
SEED_JOB_API_ID: "ulqh6w1du6"
AGENT_SERVICE_API_ID: "4k0bte7z20"
TICKET_SERVICE_API_ID: "om5u1cc0bc"

TEMP_KEY: 'bb90c867-a02e-4868-bfff-a8ef9c5f68eb2'
SEED_JOB_ID: 'ee5ca93d-a60f-4655-9bde-9fad3304cb0f'
DELETE_JOB_ID: '30b93452-71c3-4522-909b-016ea82ee13d'